### ISSUE TITLE
missing 

### ISSUE THREAD

**Issue by SanskarKashyap** [linuxdrivers/rtl8188ftv#1]
script.sh ??

**Comment by linuxdrivers** [comment]
Means that for any distro use this scripts. For example  to install in arch run arch script as arch.sh in terminal. Sent from Mail for Windows From: SanskarKashyapSent: Wednesday, April 12, 2023 3:38 PMTo: linuxdrivers/rtl8188ftvCc: SubscribedSubject: [linuxdrivers/rtl8188ftv] missing (Issue #1) script.sh ??—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by talhagdp** [comment]
Means that for any distro use this scripts. For example  to install in arch run arch script as arch.sh in terminal.
